name: Deploy to PRD server
on:
  push:
    branches:
      - test

jobs:
  compile:
    name: Call workflow compile
    uses: ./.gitea/workflows/branch-compile.yaml
    with:
      profile: test

  upload:
    needs: compile
    name: Copy to server
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: ${{ gitea.event.repository.name }}
          path: ./dist

      - name: Copy file via SSH
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ vars.G_HOST_TST }}
          username: ${{ vars.G_UID_TST }}
          key: ${{ vars.G_KEY_TST }}
          port: 22
          command_timeout: 2m
          strip_components: 1
          source: ./dist/*
          target: /home/docker/deploy/ams/html

  deploy:
    needs: upload
    name: Backup & deploy
    runs-on: ubuntu-latest
    steps:
      - name: Execute remote SSH commands
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ vars.G_HOST_TST }}
          username: ${{ vars.G_UID_TST }}
          key: ${{ vars.G_KEY_TST }}
          port: 22
          script: |
            podman exec -it ams-fe /bin/sh -c 'rm -rf /usr/share/nginx/html'
            podman cp /home/docker/deploy/ams/html ams-fe:/usr/share/nginx
            rm -rf /home/docker/deploy/ams/html